<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ShinyGo60.Builder</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShinyGo60.Builder.Core\ShinyGo60.Builder.Core.csproj" />
  </ItemGroup>
</Project>
